<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Exception Handling in Promise - 2nd way</title>
</head>
<body>
	<script type="text/javascript">

		let userAuthorized = false;

		function getUserById(id){
			return new Promise((resolve,reject)=>{
				
				if(!userAuthorized){
					throw new Error("User is not Authorized");
				}

				resolve({
					id:id,
					username:'admin'
				});
			});
		}

		try{
			getUserById().then(user=>console.log(user.username))
			.catch(error=>console.log(`Caught by .catch` + error));
		}catch(error){
			console.log(`Caught by try/catch {$error}`);
		}
	</script>
		
</body>
</html>